version: "3.11"
services:
  app:
    build:
      context: ./vendor_management
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=vendor_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7034
    ports:
      - '8000:8000'
    volumes:
      - ./vendor_management:/vendor_management
    depends_on:
      - db
    command: >
         sh -c "python manage.py wait_for_db &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:latest
    volumes:
      - vendor_database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=vendor_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7034
    container_name: vendor_database
volumes:
  vendor_database:
