# Generated by Django 4.2.8 on 2023-12-19 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import order.constants
import shortuuid.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "po_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefg1234",
                        length=10,
                        max_length=20,
                        prefix="ord",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            12,
                            20,
                            11,
                            34,
                            59,
                            893291,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("items", models.JSONField()),
                ("quantity", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (order.constants.OrderStatus["PENDING"], "pending"),
                            (order.constants.OrderStatus["COMPLETED"], "completed"),
                            (order.constants.OrderStatus["CANCELLED"], "cancelled"),
                        ],
                        default=order.constants.OrderStatus["PENDING"],
                        max_length=200,
                    ),
                ),
                ("quality_rating", models.FloatField(blank=True, null=True)),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("acknowledge_date", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="vendor.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
            },
        ),
    ]
